### ISSUE TITLE
Open Sesame Bug (PC) - Episode 3 - Marrakesh

### ISSUE THREAD

**Issue by MelvinWhite** [edisleado/Hitman-Bug-Tracker#144] opened 2016-11-19 01:22 UTC
Opportunity always fails for whatever reason. Unable to unlock the "Tourist Attractions" achievement/trophy because of this.
[https://www.youtube.com/watch?v=QQBfk59eQcU](url)
If the link doesn't work simply copy QQBfk59eQcU into YouTube search.

**Comment by wachsmuth** [comment] 2016-11-19 23:49
Duplicate of #134 , these should be merged.

**Comment by leet-it-b** [comment] 2016-11-28 15:47
Fixed in November update?
https://hitman.com/en-us/updates/november-update-release-notes

**Comment by wachsmuth** [comment] 2016-11-28 18:48
It has indeed been fixed (just tested it). Time to close this issue :)

**Closed** 2016-11-29 00:58 UTC
Labels: Gameplay, Level: Marrakesh (GC)
